const names = [
  "Rina",
  "Rina",
  "Rina",
  "Rina",
  "Rina",
  "Ernawati",
  "Ernawati",
  "Umi Udi Utami",
  "Edy",
  "Probosetyaningrum",
  "Rus Susana",
  "Yanuar Purworini",
  "Yanuar Purworini",
  "Mira Sasanti",
  "Ari Jogokaryan",
  "Nurrohmah Temanggung",
  "Nurrohmah Temanggung",
  "Rusty Waningsih",
  "Suharmi Cilacap",
  "Sri Suryaningsih",
  "Ernawati",
  "Ernawati",
  "Vico Andayani",
  "Vico Andayani",
  "Sri Hudani",
  "Sri Hudani",
  "Dini Fentini",
  "Dini Fentini",
  "Dini Fentini",
  "Cecilia Budi Maryanti",
  "Bu Yuni",
  "Sri Suryaningsih",
  "Saptati Andayani",
  "Anna Koemajasariana",
  "Anna Koemajasariana",
  "Anna Koemajasariana",
  "Rus Susana",
  "Deni Meldawati",
  "Hestudini",
  "Rina",
  "Rina",
  "Rina",
  "Rina",
  "Rina",
  "Tuti Madiun",
];

export default names;
